### PR TITLE
Manual installation doc

### PR DESCRIPTION
**Pull request by surajssd**
Added instructions to install manually for the normal usage as well as for the developer who wants to contribute.

Fixes issue #15

### CODE REVIEW

**Comment by kadel** [comment]
LGTM :+1:

**Comment by surajssd** [comment]
You are okay with the virtualenv right?

**Comment by kadel** [comment]
Yep, I'm using it myself.
Only slightly different way.
To be honest I don't know what `python setup.py develop` does. But I trust you that you do ;-)

I personally develop like this:
```
mkvirtualenv o2n
pip install -r requirments.txt
export PYTHONPATH=`pwd`:$PYTHONPATH
python openshift2nulecule/cli/main.py  .......
```

**Comment by surajssd** [comment]
@kadel yes I use `python setup.py develop` it also works nice and is also cleaner. That is I can directly use the binary openshift2nulecule and everything works fine. And changes get reflected from the binary itself.

**Pull request merged**
