### PR TITLE
Example doc for hexboard application

### PR DESCRIPTION
**Pull request by surajssd**
End to end export of Hexboard application. Deploy application in one implementation of OpenShift and
import in other instance.

### CODE REVIEW

**Comment by kadel** [comment]
From first looks it looks good. Tomorrow I'm going to go step by step and try it :wink: 

One think that I've noticed is that it might be nice to add more explanation why editing Nulecule artifacts in this case is necessary.

**Comment by surajssd** [comment]
@kadel taken care of that.

**Comment by surajssd** [comment]
@kadel could you review it?

**Comment by kadel** [comment]
@tnozicka  is going to look at this. 
I read your explanations of `$access_token` and that part is great :+1:

**Comment by surajssd** [comment]
Okay sure not a problem, Thanks @kadel

**Comment by tnozicka** [comment]
@surajssd I will look into it right after standup

**Comment by tnozicka** [comment]
@surajssd You can remove all instruction about docker registry which you don't use since you are not exporting any images.

**Comment by surajssd** [comment]
@tnozicka even I thought of this before, but then gave it up for the sake of local host registry, what has @kadel to say on this?

**Comment by kadel** [comment]
To be hones I'm not sure what is right solution for this.
One thing is that starting your own registry makes thinks much easier.
But on other hand @tnozicka pointed out important fact that we should also think about non linux users. And they cannot start registry in easy way like this.

**Comment by tnozicka** [comment]
To extent it there are two use cases
 1. Supporting OpenShift ONLY (which is this case)
 You don't need to export images since they will be re-built by OpenShift after import. We could try to avoid registry on host for this case because users on all platforms will be able to do this easily. We could go with recommending them to push AtomicApp to Openshift's internal registry (https://hub.openshift.centos7-adb.10.1.2.2.xip.io/), docker hub or their private one.

 2. Supporting OpenShift and Kubernetes
 You need to export images when you want to be importing into Kubernetes because it can't be rebuild there. In this case some type of external registry is required either natively on host or in the box with persistent storage (probably sshfs)

@surajssd @kadel Well I am not completely sure either. I like the idea of not requiring people to run their own registry in case 1 so people on Mac and Windows can try it without needing to figure out how to run docker registry in some other box and setting it all up.

This will be really easy for this case but on the other side inconsistent with rest of the cases (2).

We should probably think this thought and decide tomorrow.

**Comment by surajssd** [comment]
Maybe I can write another document for it? or another section?

**Comment by kadel** [comment]
> We could go with recommending them to push AtomicApp to Openshift's internal registry (https://hub.openshift.centos7-adb.10.1.2.2.xip.io/), docker hub or their private one.

I don't think that basically abusing OpenhShift's registry for this is good idea. It has its own set of troubles. 
First one is that namespase (project) that you want to push to must exist. For example if you have image named `hub.openshift.centos7-adb.10.1.2.2.xip.io/foo/bar` `foo` must be existing project. 
Other thing is that if you push that image, it automatically creates ImageStream. That is not necessary something bad, but I don't think that pushing to OpenShifts registry is good idea.

**Comment by kadel** [comment]
Maybe another document explaining how to get docker-registry running would
be nice.

We just need to figure out what approach is best.

For example where export is without images like in this one. I think that
best solution might be to demo it using Docker Hub.
Tell user that he/she can just push finished AtomicApp image to Docker Hub.
And maybe just mention that if he/she wants he/she can use any other
registry.

**Comment by tnozicka** [comment]
> Maybe I can write another document for it? or another section in the same document?

> I think that another document explaining how to get docker-registry running would
be nice.

@kadel @surajssd I can help and write the documentation about running registry on host (Linux) and inside another ADB/CDK (other platforms).

> I don't think that pushing to OpenShifts registry is good idea.

@kadel You are right. This is too complicated.

> But first we need to decide what is best practice for dealing with images when working with o2n.
In examples where export is without images like in this one. I think that best solution might be to demo it using Docker Hub. Tell user that he/she can just push finished AtomicApp image to Docker Hub.
With note that if he/she wants he/she can use any other registry.

I would go with Docker Hub as well for the case without images since it is the most easiest and user friendly solution.

**Comment by kadel** [comment]
I'm going to merge this, because we going to work on this with Bex

**Pull request merged**
